name: Matrix Example 
on:
  push:
  
jobs:
  Matrix-test:
    strategy:
     matrix:
      runs-on: [ubuntu-latest,windows-latest]
      python-version: [3.8,3.9]
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v5
      with:
       python-version: ${{matrix.python-version}} 

    - name: run my script
      run: python hellomessage.py