name: Catch API Data
on: [workflow_dispatch]

jobs:
  get-api-data:
    runs-on: ubuntu-latest
    steps:
      - name: Call API with curl
        id: callapi
        run: |
          response=$(curl -s https://api.github.com/repos/actions/runner/releases/latest)
          echo "Response: $response"

      - name: call terraform api
        id: terraform-api
        run: |
          response=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest)
          echo "Response: $response"
